[package]
name = "nbbs-coupon-engine"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
soroban-sdk = "26.0.1"
nbbs-shared = { path = "../shared" }
nbbs-oracle-consumer = { path = "../oracle-consumer" }

[dev-dependencies]
soroban-sdk = { version = "26.0.1", features = ["testutils"] }
nbbs-bond-issuer = { path = "../bond-issuer", features = ["testutils"] }
nbbs-project-registry = { path = "../project-registry", features = ["testutils"] }
proptest = "1"

[features]
testutils = ["soroban-sdk/testutils"]
